### ISSUE TITLE
Tracking issue for `loki.source.kubernetes`

### ISSUE THREAD

**Issue by skl** [grafana/k8s-monitoring-helm#101]
Since #61 we're no longer using `loki.source.kubernetes`, this issue tracks the possibility of using it again in future by monitoring related issues:

- https://github.com/grafana/agent/issues/4502
- https://github.com/grafana/agent/issues/4098
- https://github.com/grafana/agent/issues/5040
  - https://github.com/kubernetes/kubernetes/issues/59902
  - https://github.com/kubernetes/kubernetes/pull/118500

**Comment by petewall** [comment]
This same issue also applies to [loki.source.podlogs](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.podlogs/), so we should hold off on supporting PodLogs until the underlying issue is resolved.

If someone really needs PodLogs, it should be pretty simple to add it in with `.logs.extraConfig`

**Comment by petewall** [comment]
Perhaps we can re-enable API-delivered logs as an option.
Defaulting to DaemonSet and hostPath mounts, but have an option in the values to use the API method from the statefulset agent. This would allow for logs in clusters like Fargate, or other places where mounting host-path volumes would be prohibited.

The agent is [adding code](https://github.com/grafana/agent/pull/5623) that should address the limitation.

**Comment by petewall** [comment]
I'm going to close this. We're definitely allowing the use of API based log gathering. If that method becomes the norm, we can adjust the config as needed.
