### ISSUE TITLE
Provide a workable solution for AWS Fargate

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#188]
AWS Fargate clusters don't allow daemonsets, so Node Exporter and Grafana Agent for Logs do not run.

Just like the GKE Autopilot clusters, we can just disable node exporter.

For logs, we could look into alternatives:
* https://grafana.com/blog/2020/08/06/loki-tutorial-how-to-send-logs-from-amazons-ecs-to-loki/
* https://docs.google.com/document/d/1_927JHrzuC2QUmUkEGa2Nw5UyyL0lKC0qabB5FTjglU/edit#

This issue should result in a new example directory with guidance on how to set up a fargate cluster to get the telemetry data you want.

**Comment by petewall** [comment]
Confirmed that Node Exporter won't work, and is not expected to work:
> These metrics are inaccessible to Fargate customers since AWS is responsible for the health of the host machine.
From [Monitoring Amazon EKS on AWS Fargate using Prometheus and Grafana](https://aws.amazon.com/blogs/containers/monitoring-amazon-eks-on-aws-fargate-using-prometheus-and-grafana/)

**Comment by petewall** [comment]
As for logs, AWS lets you configure the log router using a specially named ConfigMap:
https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html

This uses fluentbit. If fluentbit was standard, this would be great! [There are ways](https://grafana.com/docs/loki/latest/send-data/fluentbit/) of configuring fluent bit to send logs to loki. However, the version of fluent bit that's being used with EKS Fargate clusters does not support that:
> You can choose between CloudWatch, ElasticSearch, Kinesis Firehose and Kinesis Streams as outputs
([source](https://aws.amazon.com/blogs/containers/fluent-bit-for-amazon-eks-on-aws-fargate-is-here/))

https://github.com/aws/aws-for-fluent-bit/issues/261
https://github.com/aws/containers-roadmap/issues/1242

Lots of folks would love to have Loki be an output source for fargate logs, but we're not there yet.

**Comment by gytis-ivaskevicius** [comment]
Hi @petewall, maybe you could help me out
I am running few system pods on Fargate and everything else is scheduled on Karpenter. Since I don't need such data on Grafana I was thinking of just blacklisting Fargate nodes log/node monitoring. Maybe easier option is to blacklist namespaces which are being scheduled there but chart does not seem to provide anything any similar configuration options

Any help would be really appreciated <3

**Comment by petewall** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Work with the Loki team to find a better way to get logs out of Fargate clusters](https://trello.com/c/qLYG2vF9/1-work-with-the-loki-team-to-find-a-better-way-to-get-logs-out-of-fargate-clusters)

**Comment by petewall** [comment]
Can you explain more about what you're looking for? What kind of telemetry data are you trying to capture from your fargate clusters?

**Comment by AllenSanbornPHR** [comment]
"Lots of folks would love to have Loki be an output source for fargate logs, but we're not there yet." 
Do you have any insight as to why this is not supported by AWS? 

We're running into this issue at the moment. We're using AWS EKS Fargate, shipping logs to CloudWatch and then scraping them from there. We'd love to simplify this for pod logs and ship them directly to Loki. 

I'm currently trolling through blog posts and GitHub issue trying to pull information together so that we can go to AWS and Grafana with our request. We're trying to avoid requiring that a sidecar and preferably a MutatingAdmissionsController to inject the sidecar, be used to hook up logging for our pods since AWS Fargate -> Fluent Bit -> Loki would be a much better solution.

**Comment by petewall** [comment]
Unfortunately, I don't have any insights as to why. Any pressure you, as a customer, can apply, the better.

In the meantime, I'm considering adding features to this chart that can offer log alternatives. In fact, we used to pull logs from the API server, rather than a daemonset with hostpath mounts. This had scaling and stability issues, but that might be resolved soon, so perhaps that could be an option that would work in this case.

**Comment by petewall** [comment]
Yes! Thank you for asking.
This Helm chart now has the ability to use the k8s api to gather logs, rather than trying to read from files. The example has been updated: https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/eks-fargate

**Comment by AllenSanbornPHR** [comment]
@petewall , A month ago I informed my AWS solutions architect about our desire to directly configure the Fargate Fluentbit configuration so that we can send logs directly to Loki. They told me that the issue is on the Fargate product roadmap. No timeline was provided. 
So... yep. Fingers crossed but no awesome news.

**Comment by petewall** [comment]
Thanks for the update! I appreciate it.
