### ISSUE TITLE
Duplicate {{release}}-test configmaps

### ISSUE THREAD

**Issue by bytheway** [grafana/k8s-monitoring-helm#207]
This caused me an issue today when upgrading the install via helm, there are 2 grafana-agent-test configmap.  Unlucky for me the normal configmap overrode the one in the helm hook leaving the hook pod without a volume to mount:

https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/templates/hooks/grafana-agent-config-test.yaml#L47

https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/templates/tests/test.yaml#L122

**Comment by petewall** [comment]
Thanks for this. I just opened this PR, which should fix it: https://github.com/grafana/k8s-monitoring-helm/pull/208

It also actually cleans things up a bit, protecting against names that might get too long, as well as consolidating the config validator into a single hook job, rather than spawning two for metrics and logs.
