### ISSUE TITLE
QUESTION: Should this chart deploy CRDs by default?

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#242]
The k8s monitoring chart deploys two sources of CRDs:
* Prometheus Operator CRDs (e.g. ServiceMonitor, PodMonitor, Probe, etc...)
* Grafana Agent CRDs (PodLogs)

This was to keep continuity with users that are migrating from Operator deployments and don't want to be forced to migrate their ServiceMonitor objects to flow components in `.extraConfig`. Since then, it seems like it's causing more trouble that it's worth.

But, I don't want to discount the idea that I'm only hearing the failures, because successful users don't often speak up.

I'm opening this up to a vote:
Should the Kubernetes Monitoring Helm chart continue to deploy CRDs by default?
👍🏻 -> Yes, keep things the way they are
👎🏻 -> No, don't deploy by default, but make it possible to deploy with a simple values file change.

**Comment by Routhinator** [comment]
While I can understand the concerns of migrating users, as someone NOT migrating from Operator, I am using this in all clusters where there is no prometheus-server deployment. I have one cluster, the primary one, that has the flag set to false because the prometheus-server chart seems to install them.

Having this be an option flag is the best way to solve this and doesn't forget every other user for the sake of one use case.

**Comment by joejulian** [comment]
Please consider https://github.com/helm/community/blob/main/hips/hip-0011.md when considering this.

One problem with managing CRDs via helm template, if you uninstall the release (say something's messed up and you want to start over), you also delete all the associated custom resources a user may have added external to this release. This runs contrary to the principal of least surprise.

**Comment by petewall** [comment]
This has been around a while and the votes to "keep things the way they are" are winning, so I'll do that.
Closing this issue.
