### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by songxychn** [grafana/k8s-monitoring-helm#280]
i use k3s, version: 1.27.7+k3s2. helm version: v3.13.1.
i followed the install instruction of https://grafana.com/solutions/kubernetes/
after i executed the install script, i got an error. script and error message are below:
```sh
helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --atomic --timeout 120s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "grafana" --create-namespace --values - <<EOF
cluster:
  name: my-cluster
externalServices:
  prometheus:
    host: https://xxx.grafana.net
    basicAuth:
      username: "xxx"
      password: xxx
  loki:
    host: https://xxx.grafana.net
    basicAuth:
      username: "xxx"
      password: xxx
opencost:
  opencost:
    exporter:
      defaultClusterId: my-cluster
    prometheus:
      external:
        url: https://xxx.grafana.net/api/prom
EOF
```
```
Error: Unable to continue with install: 
CustomResourceDefinition "podmonitors.monitoring.coreos.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; 
label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; 
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "grafana-k8s-monitoring"; 
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "grafana"
```
i've searched on google, and most viewpoints are that i created the resources beyond the control of helm. but i found nothing new when i use `kubectl get all --all-namespaces`
your help will be appreciated!

**Comment by daveram** [comment]
Good timing I just tried installing this on my RKE2 cluster, almost the same error except mine had "alertmanagers.monitoring.coreos.com" instead of "podmonitors.monitoring.coreos.com" for CRD

`
Error: rendered manifests contain a resource that already exists. Unable to continue with install:
CustomResourceDefinition "alertmanagers.monitoring.coreos.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; 
label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm";
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "grafana-k8s-monitoring";
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "grafanacloud"
`

**Comment by skl** [comment]
I think it's because the CRDs already exist, so the helm chart fails when it attempts to deploy them. Try setting [prometheus-operator-crds.enabled](https://github.com/grafana/k8s-monitoring-helm/blob/4b301e55ff569d25a03daa96ded89b08131baf70/charts/k8s-monitoring/values.yaml#L835-L842) to `false`:

```yaml
prometheus-operator-crds:
  enabled: false
```

Also see:

- #242

**Comment by songxychn** [comment]
> Yeah, it's something that we see somewhat frequently:是的，这是我们经常看到的东西： https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/Troubleshooting.md

thanks

**Comment by songxychn** [comment]
> I think it's because the CRDs already exist, so the helm chart fails when it attempts to deploy them. Try setting [prometheus-operator-crds.enabled](https://github.com/grafana/k8s-monitoring-helm/blob/4b301e55ff569d25a03daa96ded89b08131baf70/charts/k8s-monitoring/values.yaml#L835-L842) to `false`:
> 
> ```yaml
> prometheus-operator-crds:
>   enabled: false
> ```
> 
> Also see:
> 
> * [QUESTION: Should this chart deploy CRDs by default? #242](https://github.com/grafana/k8s-monitoring-helm/issues/242)

thanks! and i wonder how can i know the crds i need to disable when i see this error next time? i don't see the connection between the error log and `prometheus-operator-crds`

**Comment by skl** [comment]
@songxychn we previously had a more informative error message but this was incompatible with ArgoCD, see:

- #234
- #253

**Comment by Lawouach** [comment]
Hi, I'm still seeing this using Grafana cloud instructions on a fresh microk8s install. Is there an actual response to this?
