### ISSUE TITLE
Question: Node exporter subchart vs prometheus.exporter.unix component

### ISSUE THREAD

**Issue by marshallford** [grafana/k8s-monitoring-helm#373]
As the title suggests I have a question rather than a feature request or bug report, hopefully a GH issue is the appropriate place. 

Anyways, I'm curious why the node exporter helm chart is utilized to produce node metrics rather than the Grafana Agent component `prometheus.exporter.unix`. I see that the component is already being used, but just for producing an `info` metric via the `textfile` collector. Prior to stumbling onto this repository/umbrella chart I figured the "best practice" would be to use the component in place of the standalone chart, even if that meant in some cases deploying an additional copy of Grafana Agent as a DaemonSet. I'd think fewer container images, config formats, and charts would make configuration and maintenance simpler for k8s cluster admins/operators. Thoughts?

Thank you all for maintaining this chart, I especially appreciate the extracted config files that are kept up to date for each example -- great idea and very helpful!

**Comment by petewall** [comment]
This is a good question, and I debated whether to use the Agent's internal exporter instead.

Certainly the pro's for using the agent mean one less daemonset deployment and fewer container images, simpler config, etc..

However, the reasons I ultimately went with a separate node exporter deployment were because of these reasons:

1. It brings flexibility in how the Grafana Agent that scrapes metrics can be deployed. If it uses the unix exporter component, it *needs* to be a DaemonSet. Right now, it can be a StatefulSet and can be horizontally scaled to handle resource requirements.
1. Some clusters often already have Node Exporter deployed, like OpenShift. The chart is flexible to use pre-existing node exporters and skip deploying the one locally.
1. It compartmentalizes the work being done. For the most part, the Agent is there to *only* gather telemetry data (metrics, logs, traces, and events). Let other components do what they do best and let the agent find and gather that data.

Hopefully this helps answer your question. Thank you for posting it. This was a perfect place for it.

**Comment by marshallford** [comment]
Thanks for the insights! A follow up question if you don't mind:

Do you foresee any issues or initial roadblocks with using `prometheus.exporter.unix` instead (for those willing to venture off the path that this chart paves)? I'm thinking of situations where the environment is resource constrained, node-exporter is not present, and Grafana Agent is already configured to run as a DaemonSet for container logs.

**Comment by petewall** [comment]
I don't foresee any issues. If you wanted to convert an agent to use prometheus.exporter instead of node exporter, you'd like have to do the following:
1. Turn off node exporter (`metrics.node-exporter.enabled=false` && `node-exporter.enabled=false`)
2. Change the grafana agent to be a daemonset (`grafana-agent.controller.type=daemonset` IIRC)
3. Set the right RBAC and pod security contexts
4. Add the prometheus.exporter component and likely a prometheus.relabel component for post-processing/filtering.

**Comment by petewall** [comment]
Closing as this has been a month and it's been answered.
