### ISSUE TITLE
Question: Finding metric targets via prometheus.operator.* or discovery.kubernetes.*

### ISSUE THREAD

**Issue by marshallford** [grafana/k8s-monitoring-helm#381]
Hello again! While reviewing the [default `metrics.river` config](https://github.com/grafana/k8s-monitoring-helm/blob/main/examples/default-values/metrics.river) I noticed that for the handful of services that export cluster/system metrics (node-exporter, etc) the `discovery.kubernetes.*` and `discovery.relabel` components are used to find the relevant targets for said services. Similarly, I also noted that the default config includes the use of the `prometheus.operator.*` components to find targets via the Prometheus Operator CRs -- which among other benefits mitigates the need to add `discover.*` components to an ever growing config. 

Assuming I have that all straight, I'll get to my actual question: Given that the helm charts for kube-state-metrics, node-exporter, opencost, and even grafana-agent itself all include `ServiceMonitor` resources, why write configuration to scrape those targets when the helm chart already provides the information on how to scrape the services? In addition, any concern the targets will be scraped twice (if any of the helm charts mentioned enable the creation of the `ServiceMonitor` by default)?

Thanks!

**Comment by petewall** [comment]
Yes, there is the chance for double-scraping. But I think it's worth the risk considering:
1. This chart controls the deployment of Node Exporter, Kube-State-Metrics, OpenCost, and the Agents. So we can turn those off by default.
2. This chart aims to be a easy replacement for people who are used to instrumenting their cluster with: Grafana Agent Operator, Kube-prometheus-stack, and many other implementations. I wanted to have ServiceMonitor support in order to minimize the effort needed to "convert" everything, especially custom application metrics.

It's making me think of ways to minimize double-scraping, though. Perhaps there's a test that can be added to `helm test` that can check if a metric like `kube-node-info` is being scraped, but coming from multiple sources.
