### ISSUE TITLE
Restart Grafana StatefulSet on agent config changes

### ISSUE THREAD

**Issue by sidewinder12s** [grafana/k8s-monitoring-helm#405]
If the Helm chart is updated with a new agent configmap & there is an error in that config, the grafana agent will not crash until it is restarted. 

This leads to seemingly correct configs being landed/applied and the feedback that it is wrong is not surfaced until the agent is restarted. 

Either the Grafana agent config check job should fail or the Grafana agent should be restarted so that it will fail loudly when testing.

**Comment by petewall** [comment]
Hey! Thanks for the issue. Actually, the `config-reloader` sidecar should handle updating the running agent to use the latest config if it updates. However, the Agent was designed to stay online and running, rather than changing to a broken config.

The Helm chart has a config validator pre-install / pre-upgrade hook that runs when you deploy. Currently, it only checks for syntax errors, not for config correctness. I'm hopeful that a future version of the Agent will include a stronger config validator.

**Comment by sidewinder12s** [comment]
How is someone supposed to discover that they've landed an incorrect configuration?

**Comment by petewall** [comment]
There isn't an easy method at the moment.
push for https://github.com/grafana/agent/issues/3844 to be implemented so it can be added to the pre-install/pre-upgrade hook.
I have some ideas, which would involve running the agent for a moment and seeing if it crashes. I do that locally if you run `make test`, but it's harder to do on an actual cluster.

**Comment by sidewinder12s** [comment]
Just tested it, caught invalid config during the pre-sync hook.

**Comment by petewall** [comment]
Nice! Glad we could get this stronger validation working.
