### ISSUE TITLE
Compatibility matrix for grafana

### ISSUE THREAD

**Issue by smyja** [grafana/k8s-monitoring-helm#573]
Where can i find a Table showing the various grafana versions and their supported kubernetes versions like some cncf projects?

**Comment by petewall** [comment]
Are you asking about [Grafana](https://grafana.com/oss/grafana/) itself, or this Helm chart (the k8s-monitoring Helm chart)?

**Comment by smyja** [comment]
Both

**Comment by petewall** [comment]
I don't believe that any compatibility matrix exists today. From my gathering, both charts should be compatible with all currently supported versions of Kubernetes.

Is there a specific version or use case that you're interested in?

**Comment by petewall** [comment]
As of now, the k8s-monitoring Helm chart has been tested back to 1.19, so it should be compatible with nearly every supported version.

**Comment by ubbeK** [comment]
> As of now, the k8s-monitoring Helm chart has been tested back to 1.19, so it should be compatible with nearly every supported version.

That is nice! But are you guys planning to add something like this in the future?

Examples:
* https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases
* https://cert-manager.io/docs/releases/
* https://external-secrets.io/latest/introduction/stability-support/

**Comment by nichoio** [comment]
Agree with the previous post. There should be some kind of documentation which versions of K8s the Grafana Monitoring chart was tested against. This info should not only be buried in a Github discussion.
Because Kubernetes minor upgrades have to be performed regularly and are hard to impossible to roll back, cluster admins need certainty that the Helm charts installed are known to work with the target K8s version.
