### ISSUE TITLE
Kubelet and cAdvisor don't work if default cluster domain is not supported

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#65]
If the cluster does not use `cluster.local`, then the kubelet and cadvisor will not work correctly.

Both these metric sources work by querying all nodes, but changing the target address and path to:
* `__address__`: `kubernetes.default.svc.cluster.local:443` (The kubernetes service in the default namespace)
* `__path__`: `/api/v1/nodes/<node>/proxy/metrics`  (A path for that service that references the node)

So, while we discover the nodes, we hard-code the kubernetes service.

If the user's cluster's internal DNS does something like `kubernetes.default.svc.my-prod-cluster.local:443`, the hardcoded service address will be wrong.

**Comment by petewall** [comment]
Potential change:
```
% git diff
diff --git a/charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt b/charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt
index 49eb437..f558ad4 100644
--- a/charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt
+++ b/charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt
@@ -4,7 +4,7 @@ discovery.relabel "cadvisor" {
   targets = discovery.kubernetes.nodes.targets
   rule {
     target_label = "__address__"
-    replacement  = "kubernetes.default.svc.cluster.local:443"
+    replacement  = "kubernetes.default.svc:443"
   }
   rule {
     source_labels = ["__meta_kubernetes_node_name"]
diff --git a/charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt b/charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt
index bc33931..cc0c2eb 100644
--- a/charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt
+++ b/charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt
@@ -4,7 +4,7 @@ discovery.relabel "kubelet" {
   targets = discovery.kubernetes.nodes.targets
   rule {
     target_label = "__address__"
-    replacement  = "kubernetes.default.svc.cluster.local:443"
+    replacement  = "kubernetes.default.svc:443"
   }
   rule {
     source_labels = ["__meta_kubernetes_node_name"]
```

**Comment by skl** [comment]
I presume removing the `.cluster.local` works because a DNS search domain is configured somewhere in k8s... checking the [docs](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#dns-windows), this seems to be true BUT there's a caveat with Windows nodes.

Linux node on EKS:

```shell
root@windows-split-grafana-agent-0:/# getent hosts kubernetes
10.100.0.1      kubernetes.default.svc.cluster.local
root@windows-split-grafana-agent-0:/# getent hosts kubernetes.default
10.100.0.1      kubernetes.default.svc.cluster.local
root@windows-split-grafana-agent-0:/# getent hosts kubernetes.default.svc
10.100.0.1      kubernetes.default.svc.cluster.local
root@windows-split-grafana-agent-0:/# getent hosts kubernetes.default.svc.cluster
root@windows-split-grafana-agent-0:/# getent hosts kubernetes.default.svc.cluster.local
10.100.0.1      kubernetes.default.svc.cluster.local
```

So only `kubernetes.default.svc.cluster` failed to resolve.

For Windows, from what I can read up on, it seems to be CNI-dependent (so different behaviour on AKS than on EKS). At least for EKS on the same cluster above but on a Windows node, I find that actually ONLY the FQDN `kubernetes.default.svc.cluster.local` resolves and only when I explicitly state the cluster IP of a coredns pod like this:

```shell
Resolve-DnsName -Name kubernetes.default.svc.cluster.local -Server 192.168.24.32

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
kubernetes.default.svc.cluster.local           A      5     Answer     10.100.0.1
```

Even if I try and set additional search domains using `Set-DnsClientGlobalSetting -SuffixSearchList @("default.svc.cluster.local", "svc.cluster.local", "cluster.local")` it doesn't seem to help the issue.

So, at least to be in line with the k8s docs on the matter, I'd recommend using the lowest common demonator which is just `kubernetes` - hopefully that covers the most cases. This avoids usage of a `.` which apparently prevents Windows from even using search domains at all.

**Comment by petewall** [comment]
At least, until Flow supports [data transformations](https://github.com/grafana/agent/issues/2783), which would let us "discover" the kubernetes service and use that along with the discovered nodes to build a combined target list meant for scraping.

**Comment by skl** [comment]
+1 I'm happy with just specifying the FQDN as a value.
