### ISSUE TITLE
Adding full Endpoint into K8S Monitoring HELM values results in 404

### ISSUE THREAD

**Issue by lionelmarksgrafana** [grafana/k8s-monitoring-helm#683]
Seems like there's an issue where api/prom/push is appended to the helm value 

`grafana-alloy.k8s-monitoring.externalServices.prometheus.host=https://prometheus-us-central1.grafana.net/api/prom/push`

<img width="557" alt="Screenshot 2024-08-09 at 12 37 48 PM" src="https://github.com/user-attachments/assets/1a5c8c78-fa51-4de4-96d6-80997eb68cd6">

<img width="1309" alt="Screenshot 2024-08-09 at 12 40 35 PM" src="https://github.com/user-attachments/assets/0e11643e-48d8-4ccc-a4d0-d353c57e0ab7">

**Comment by petewall** [comment]
This is basically the same at https://github.com/grafana/k8s-monitoring-helm/issues/282

The reason I went with the bare host instead of write URL was that it let me build URLs for both writing as well as querying. I realized later that this causes a bit of a copy-paste problem, where Grafana Cloud shows the prometheus URL with the path.
