### ISSUE TITLE
Add an example that uses an environment variable set in Alloy

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#688]
People are asking for it...

**Comment by jark-AB** [comment]
+1 would also like to see how we can use generic envVars into the Alloy helm chart. We need to construct the postgres host string:
https://github.com/fr3fou/home/blob/23e0c81c198e26d6ef325d386a187e29eed4acd1/apps/alloy/alloy.yaml#L98

**Comment by fr3fou** [comment]
yeah, I'm having issues with this as well. exactly with the line @jark-AB linked :D 

may I ask, how did you come across my repository?

**Comment by petewall** [comment]
Honestly, in your example, it might be better to create a Kubernetes Secret with those variables, then use `remote.kubernetes.secret` to discover it and then string concatenation to create the connection string.

Using environment variables is great and all, but not always ideal for passing secrets.

**Comment by jark-AB** [comment]
> yeah, I'm having issues with this as well. exactly with the line @jark-AB linked :D
> 
> may I ask, how did you come across my repository?

I was grepping around on users that use the `prometheus.postgres` exporter since we were trying to add that to Grafana Alloy and the docs weren't too clear on how to implement that. Docs instead use a sql configMap after more researching:
https://github.com/grafana/k8s-monitoring-helm/blob/eacedb97921698849301f1eb16575b242e8069dc/.github/configs/mysql-config.yaml#L59

However, we are n servers to x set of credentials and need to loop through a server + associated secretManager. So what we ended up doing is abstract this out to prom-postgres-exporter helm chart. That will be deployed and the service scraped by Alloy
