### ISSUE TITLE
Any plans for monitoring CoreDNS?

### ISSUE THREAD

**Issue by ufou** [grafana/k8s-monitoring-helm#816]
Hi,

I notice that we don't have monitoring for CoreDNS included with this wonderful chart, I can see that someone mentioned it in https://github.com/grafana/k8s-monitoring-helm/issues/148 and as part of that other kube-system/control-panel components are now monitored, like api, controller-manager and scheduler but not CoreDNS, are there plans to introduce this?

Or should I try to add a custom section as detailed in https://grafana.com/docs/grafana-cloud/monitor-infrastructure/integrations/integration-reference/integration-coredns/

Thanks

**Comment by petewall** [comment]
Currently, it's not built-in, but I could see adding it. In the meantime, you can try adding the snippets into the `extraConfig` sections to discover, scrape, process, and deliver the CoreDNS metrics.

**Comment by ufou** [comment]
Yeah, I was going to add the `extraConfig` snippet but when I tested it I couldn't get it working, most likely I did something wrong, anyhow I elected to use a serviceMonitor instead, we already deploy a few of those so it was a fairly simple solution to add one for CoreDNS monitoring, thanks!

**Comment by Jeansen** [comment]
I'd be happy to see this implemented. It works with ServiceMonitors, but having it alongside the other components like kubelet, apiserver etc. would make a lot of sense. Otherwise it's a mixture of configurations. Some parts are configured in the values file others with other means. Even doing it with the `extraConfig` does not feel clean to me.
