### ISSUE TITLE
Beyla + Profiling on a single Daemonset

### ISSUE THREAD

**Issue by sidewinder12s** [grafana/k8s-monitoring-helm#845]
Is my read correct that if you deploy Beyla and the Continuous Profiling configs through this chart that it is going to deploy 2 seperate daemonsets?

**Comment by petewall** [comment]
Yes that is correct. That is because a "soft" design rule is to keep each component doing only what they do best, even when that means more deployments. Beyla is there to do auto-instrumentation, and (for the most part) Alloy is there to collect, process, and deliver the data. I try not to use it as a data generator. That being said, profiling doesn't have a standalone component, just Alloy, so that's why its in there.

**Comment by sidewinder12s** [comment]
The only comment I would make about this design is that maybe it should be re-evaluated for DaemonSets. They carry significantly higher costs in their design than just adding dedicated deployments per component on nodes, compute overhead, IP address utilization, etc.
