### ISSUE TITLE
Clustering should be enabled by default for alloy-pods

### ISSUE THREAD

**Issue by cyriltovena** [grafana/k8s-monitoring-helm#897]
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring-v1/values.yaml#L2685-L2687

Based on the comment it assumes the clustering should off because by default people don't use Loki input that needs clustering but when they do it result in duplicate logs.

We should either:
- Make clustering on by default
- Use the same clustering value as alloy.
- Validate if alloy is configured for clustering, then clustering should also be on for `alloy-logs`

**Comment by petewall** [comment]
We actually used to enabled clustering by default for all Alloy instances. Just in case that a user switches to a config that can utilize clustering. However, we turned it off in 7ec6d61 because it adds overhead for coordinating jobs that never utilize clustering.

The chart does have some guardrails to fail deployment if you change pod log gathering to something that can use clustering (gathering via the Kubernetes API), it'll tell you to enable clustering, and if you enable clustering, but are using the daemonset to gather logs from the hostpath volume mount, it'll tell you to disable clustering.

If those checks aren't working, I'd definitely like to know!
